### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by skinlayers** [HeavyHorst/remco#18]
I apologize in advance if this isn't the best place to be asking this.

The Project Status in README.md states that remco is under active development, and not recommended for production use . However, there has not been a commit since Nov 1st, 2017. Is remco still under active development? Are the lack of recent commit an indicator that remco has reach maturity?

**Comment by HeavyHorst** [comment]
Hey, tanks for the interest in remco!

remco currently has all the features I need and apart from me there don't seem to be many people using it, so there are very few issues and pull requests.

I left the note in the Readme until now, because nobody else seems to use the software - so its probably not very well tested in the wild.
But i'm still maintaining remco and would be glad to hear some feedback via issues or see some pull requests.
